
server:
  port: 8080
spring:
  datasource:
    local:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@47.99.191.156:1521:DUPDB
      username: appsquery
      password: appsquery
    remote:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@47.99.191.156:1521:STANDBY
      username: appsquery
      password: appsquery

mybatis:
  mapper-locations: classpath:/com/lxf/migration/mapper/*.xml
  type-aliases-package: com.lxf.migration.pojo


